#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::Path;

use repository::generated::{
    classify_generated, GeneratedConfig, GeneratedFacts, GeneratedKind, GeneratedReason,
    GitAttributesView,
};
use repository::read::BoundedReader;
use repository::tsconfig::detect_tsconfigs;
use repository::walk::{walk, WalkOptions};
use review_core::location::RepoPath;
use review_test_support::{edge_case_tree, write_file};

fn classify(root: &Path, cfg: &GeneratedConfig) -> GeneratedFacts {
    let (inv, _) = walk(root, &WalkOptions::default()).unwrap();
    let reader = BoundedReader::new(&inv.root);
    let (ts, _) = detect_tsconfigs(&inv, &reader);
    let attrs = GitAttributesView::from_inventory(&inv, &reader);
    classify_generated(&inv, &ts, &attrs, cfg, &reader).0
}

fn get<'a>(
    facts: &'a GeneratedFacts,
    path: &str,
) -> Option<&'a repository::generated::GeneratedClass> {
    facts.files.get(&RepoPath::new(path).unwrap())
}

fn edge() -> (tempfile::TempDir, GeneratedFacts) {
    let tmp = edge_case_tree();
    let facts = classify(tmp.path(), &GeneratedConfig::default());
    (tmp, facts)
}

#[test]
fn dist_dir_generated() {
    let (_t, facts) = edge();
    let class = get(&facts, "dist/bundle.js").unwrap();
    assert_eq!(class.kind, GeneratedKind::Generated);
    assert!(matches!(&class.reason, GeneratedReason::Directory { name } if name == "dist"));
    assert!(get(&facts, "coverage/lcov.info").is_some());
    assert!(facts
        .dirs
        .iter()
        .any(|(d, k, n)| d.as_str() == "dist" && *k == GeneratedKind::Generated && *n == 2));
}

#[test]
fn ts_out_dir_generated() {
    let tmp = tempfile::tempdir().unwrap();
    write_file(
        tmp.path(),
        "tsconfig.json",
        r#"{"compilerOptions":{"outDir":"./compiled"}}"#,
    );
    write_file(tmp.path(), "compiled/main.js", "var a;\n");
    write_file(tmp.path(), "src/main.ts", "export {};\n");
    let facts = classify(tmp.path(), &GeneratedConfig::default());
    let class = get(&facts, "compiled/main.js").unwrap();
    assert!(
        matches!(&class.reason, GeneratedReason::TsOutDir { dir } if dir.as_str() == "compiled")
    );
    assert_eq!(class.confidence, 0.9);
    assert!(get(&facts, "src/main.ts").is_none());
}

#[test]
fn vendor_dir_vendored() {
    let (_t, facts) = edge();
    let class = get(&facts, "vendor/lib.js").unwrap();
    assert_eq!(class.kind, GeneratedKind::Vendored);
}

#[test]
fn at_generated_header_canonical() {
    let (_t, facts) = edge();
    // src/generated/client.ts is also in a `generated` directory; the header wins by precedence.
    let class = get(&facts, "src/generated/client.ts").unwrap();
    assert_eq!(
        class.reason,
        GeneratedReason::Header {
            marker: "@generated".to_owned(),
            line: 1
        }
    );
    assert_eq!(class.confidence, 0.95);
}

#[test]
fn go_code_generated_marker_with_hint() {
    let (_t, facts) = edge();
    let class = get(&facts, "api.pb.go").unwrap();
    assert!(matches!(class.reason, GeneratedReason::Header { .. }));
    assert_eq!(class.generator_hint.as_deref(), Some("protoc-gen-go"));
}

#[test]
fn do_not_edit_without_generated_word_not_flagged() {
    let (_t, facts) = edge();
    assert!(get(&facts, "src/constants.ts").is_none());
}

#[test]
fn header_outside_comment_ignored() {
    let tmp = tempfile::tempdir().unwrap();
    write_file(
        tmp.path(),
        "src/a.ts",
        "export const marker = \"@generated\";\nexport const b = \"DO NOT EDIT auto-generated\";\n",
    );
    write_file(tmp.path(), "src/b.ts", "// @generated\nexport {};\n");
    let facts = classify(tmp.path(), &GeneratedConfig::default());
    assert!(get(&facts, "src/a.ts").is_none());
    assert!(get(&facts, "src/b.ts").is_some());
}

#[test]
fn loose_marker_needs_generat_word() {
    let tmp = tempfile::tempdir().unwrap();
    write_file(
        tmp.path(),
        "a.py",
        "# auto-generated by tool, DO NOT EDIT\n",
    );
    let facts = classify(tmp.path(), &GeneratedConfig::default());
    let class = get(&facts, "a.py").unwrap();
    assert_eq!(class.confidence, 0.7);
}

#[test]
fn lockfiles_classified() {
    let (_t, facts) = edge();
    let class = get(&facts, "package-lock.json").unwrap();
    assert_eq!(class.kind, GeneratedKind::Lockfile);
    assert_eq!(class.confidence, 1.0);
}

#[test]
fn min_js_minified() {
    let (_t, facts) = edge();
    assert_eq!(
        get(&facts, "assets/app.min.js").unwrap().kind,
        GeneratedKind::Minified
    );
}

#[test]
fn gitattributes_linguist_generated_true_and_false() {
    let (_t, facts) = edge();
    let plain = get(&facts, "src/plain.ts").unwrap();
    assert!(matches!(
        &plain.reason,
        GeneratedReason::GitAttributes { attribute } if attribute == "linguist-generated"
    ));
    // `-linguist-generated` forces src/generated/forced.ts out of the generated directory.
    assert!(get(&facts, "src/generated/forced.ts").is_none());
}

#[test]
fn config_exclude_beats_header() {
    let tmp = edge_case_tree();
    let cfg = GeneratedConfig {
        exclude: vec!["src/generated/client.ts".to_owned()],
        include: Vec::new(),
    };
    let facts = classify(tmp.path(), &cfg);
    assert!(get(&facts, "src/generated/client.ts").is_none());
    // An exclude also beats a config include.
    let cfg = GeneratedConfig {
        exclude: vec!["src/app.ts".to_owned()],
        include: vec!["src/**".to_owned()],
    };
    let facts = classify(tmp.path(), &cfg);
    assert!(get(&facts, "src/app.ts").is_none());
    assert!(get(&facts, "src/constants.ts").is_some());
}

#[test]
fn config_include_glob() {
    let tmp = edge_case_tree();
    let cfg = GeneratedConfig {
        include: vec!["packages/a/**".to_owned(), "[".to_owned()],
        exclude: Vec::new(),
    };
    let (inv, _) = walk(tmp.path(), &WalkOptions::default()).unwrap();
    let reader = BoundedReader::new(&inv.root);
    let (ts, _) = detect_tsconfigs(&inv, &reader);
    let attrs = GitAttributesView::from_inventory(&inv, &reader);
    let (facts, warnings) = classify_generated(&inv, &ts, &attrs, &cfg, &reader);
    let class = get(&facts, "packages/a/index.ts").unwrap();
    assert!(matches!(
        class.reason,
        GeneratedReason::ConfigInclude { .. }
    ));
    assert!(warnings.iter().any(|w| w.code == "invalid_generated_glob"));
}

#[test]
fn precedence_reason_is_explainable() {
    let (_t, facts) = edge();
    let reasons: Vec<(String, &str)> = facts
        .files
        .iter()
        .map(|(p, c)| (p.as_str().to_owned(), c.reason.label()))
        .collect();
    insta::assert_yaml_snapshot!(reasons);
}
