#!/usr/bin/env node
// Generates TypeScript types from the JSON Schemas exported by `review contracts export`.
//   node scripts/generate.mjs [--schemas <dir>] [--out <dir>]
// Defaults: schemas/ -> src/generated/. Output is deterministic.
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const PKG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BANNER = '/* GENERATED by packages/contracts/scripts/generate.mjs — do not edit */';

/** Generate TS files for every `*.schema.json` in `schemasDir` into `outDir`. */
export async function generate(schemasDir, outDir) {
  const names = (await readdir(schemasDir))
    .filter((f) => f.endsWith('.schema.json'))
    .map((f) => f.slice(0, -'.schema.json'.length))
    .sort();

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  for (const name of names) {
    const schema = JSON.parse(await readFile(path.join(schemasDir, `${name}.schema.json`), 'utf8'));
    const ts = await compile(schema, name, {
      bannerComment: BANNER,
      additionalProperties: false,
      strictIndexSignatures: true,
      format: true,
      cwd: schemasDir,
    });
    await writeFile(path.join(outDir, `${name}.ts`), ts);
  }

  const barrel = [BANNER, ...names.map((n) => `export type * from './${n}.js';`), ''].join('\n');
  await writeFile(path.join(outDir, 'index.ts'), barrel);
  return names;
}

function arg(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? path.resolve(process.argv[i + 1]) : fallback;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const schemas = arg('--schemas', path.join(PKG, 'schemas'));
  const out = arg('--out', path.join(PKG, 'src', 'generated'));
  generate(schemas, out).then(
    (names) => console.log(`generated ${names.length} contract type(s) into ${out}`),
    (err) => {
      console.error(err);
      process.exit(1);
    },
  );
}
