/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CandidateFindings {
  affected_symbols: Generated<string[]>;
  category: string;
  changed_end_line: number;
  changed_path: string;
  changed_side: string;
  changed_start_line: number;
  confidence_candidate: number | null;
  created_at: Generated<Timestamp>;
  description: string;
  evidence: Generated<Json>;
  fingerprint: string;
  id: Generated<string>;
  organization_id: string;
  reasoning_artifacts: Generated<Json>;
  review_run_id: string;
  reviewer: string;
  reviewer_run_id: string;
  severity_candidate: string;
  state: string;
  suppressed_at_stage: number | null;
  suppression: Json | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface FindingFeedback {
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  published_finding_id: string;
  source: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  verdict: string;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  organization_id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface ProviderInstallations {
  account_login: string;
  account_type: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  permissions: Generated<Json>;
  provider: string;
  provider_installation_id: Int8;
  suspended_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface PublishedFindings {
  created_at: Generated<Timestamp>;
  end_line: number | null;
  head_sha: string;
  id: Generated<string>;
  organization_id: string;
  path: string | null;
  placement: string;
  provider: string;
  provider_comment_id: string | null;
  provider_review_id: string | null;
  published_at: Timestamp;
  pull_request_id: string;
  review_run_id: string;
  start_line: number | null;
  updated_at: Generated<Timestamp>;
  verified_finding_id: string;
}

export interface PullRequests {
  author_login: string;
  base_ref: string;
  base_sha: string;
  created_at: Generated<Timestamp>;
  draft: Generated<boolean>;
  head_ref: string;
  head_sha: string;
  id: Generated<string>;
  merge_base_sha: string | null;
  organization_id: string;
  provider_number: number;
  repository_id: string;
  state: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Repositories {
  archived: Generated<boolean>;
  created_at: Generated<Timestamp>;
  default_branch: string;
  full_name: string;
  id: Generated<string>;
  installation_id: string;
  organization_id: string;
  provider: string;
  provider_repo_id: string;
  settings: Generated<Json>;
  updated_at: Generated<Timestamp>;
  visibility: string;
}

export interface ReviewerRuns {
  cached_read_tokens: Generated<Int8>;
  cached_write_tokens: Generated<Int8>;
  cluster_key: string | null;
  cost_usd_micros: Generated<Int8>;
  created_at: Generated<Timestamp>;
  error_class: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input_tokens: Generated<Int8>;
  latency_ms: number | null;
  model: string | null;
  organization_id: string;
  output_tokens: Generated<Int8>;
  prompt_version: string | null;
  provider: string | null;
  review_run_id: string;
  reviewer: string;
  reviewer_version: string | null;
  started_at: Timestamp | null;
  state: string;
  updated_at: Generated<Timestamp>;
}

export interface ReviewRuns {
  base_sha: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  degraded_reviewers: Generated<string[]>;
  failure_class: string | null;
  failure_detail: string | null;
  head_sha: string;
  id: Generated<string>;
  merge_base_sha: string | null;
  organization_id: string;
  provenance: Generated<Json>;
  pull_request_id: string;
  repository_id: string;
  retry_of: string | null;
  state: string;
  superseded_by: string | null;
  trace_parent: string | null;
  trigger: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string | null;
  id: Generated<string>;
  login: string;
  provider: string;
  provider_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface VerifiedFindings {
  band: string;
  candidate_finding_id: string;
  computed_confidence: number;
  created_at: Generated<Timestamp>;
  evidence: Json;
  id: Generated<string>;
  organization_id: string;
  priority_score: number | null;
  review_run_id: string;
  severity: string;
  stage_outcomes: Json;
  updated_at: Generated<Timestamp>;
  verification_version: number;
}

export interface WebhookDeliveries {
  action: string | null;
  created_at: Generated<Timestamp>;
  delivery_id: string;
  error: string | null;
  event: string;
  id: Generated<string>;
  organization_id: string | null;
  payload_sha256: string;
  processed_at: Timestamp | null;
  provider: string;
  provider_installation_id: Int8 | null;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  candidate_findings: CandidateFindings;
  finding_feedback: FindingFeedback;
  memberships: Memberships;
  organizations: Organizations;
  provider_installations: ProviderInstallations;
  published_findings: PublishedFindings;
  pull_requests: PullRequests;
  repositories: Repositories;
  review_runs: ReviewRuns;
  reviewer_runs: ReviewerRuns;
  users: Users;
  verified_findings: VerifiedFindings;
  webhook_deliveries: WebhookDeliveries;
}
