/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_type: string;
  hash: Buffer | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  organization_id: string;
  outcome: Generated<string>;
  prev_hash: Buffer | null;
  repository_id: string | null;
  request_id: string | null;
  target_id: string | null;
  target_type: string;
  trace_id: string | null;
}

export interface CandidateFindings {
  affected_symbols: Generated<string[]>;
  category: string;
  changed_end_line: number;
  changed_path: string;
  changed_side: string;
  changed_start_line: number;
  confidence_candidate: number | null;
  created_at: Generated<Timestamp>;
  description: string;
  evidence: Generated<Json>;
  fingerprint: string;
  id: Generated<string>;
  organization_id: string;
  reasoning_artifacts: Generated<Json>;
  review_run_id: string;
  reviewer: string;
  reviewer_run_id: string;
  severity_candidate: string;
  state: string;
  suppressed_at_stage: number | null;
  suppression: Json | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface EdgeKinds {
  id: number;
  name: string;
}

export interface FileVersions {
  analyzer_version: string;
  content_hash: Buffer;
  created_at: Generated<Timestamp>;
  diagnostic_count: Generated<number>;
  id: Generated<Int8>;
  language: string;
  organization_id: string;
  parse_status: string;
  path: string;
  repository_id: string;
  size_bytes: number;
  symbol_count: Generated<number>;
}

export interface FindingFeedback {
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  published_finding_id: string;
  source: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  verdict: string;
}

export interface GraphEdges {
  col: number | null;
  confidence: number;
  file_version_id: Int8 | null;
  flags: Generated<number>;
  kind: number;
  line: number | null;
  occurrences: Generated<number>;
  organization_id: string;
  origin_path: string | null;
  provenance: number;
  removed: Generated<boolean>;
  resolved_by: number;
  snapshot_id: string;
  source_key: Buffer;
  target_key: Buffer;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  organization_id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ModelCache {
  cache_key: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  model: string;
  organization_id: string;
  output: Json;
  prompt_version: string;
  provider: string;
  request_hash: string;
  schema_hash: string | null;
  usage: Json;
}

export interface ModelCalls {
  attempt: number;
  cache_read: number;
  cache_write: number;
  cost_usd_micros: Int8 | null;
  created_at: Generated<Timestamp>;
  id: string;
  input_uncached: number;
  latency_ms: number;
  model: string;
  organization_id: string;
  outcome: string;
  output_tokens: number;
  prices_as_of: Timestamp | null;
  provider: string;
  repository_id: string;
  request_hash: string;
  review_run_id: string | null;
  reviewer_run_id: string | null;
  served_from: string;
  task: string;
  tier: string;
}

export interface NodeKinds {
  id: number;
  name: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface ProvenanceKinds {
  id: number;
  name: string;
}

export interface ProviderInstallations {
  account_login: string;
  account_type: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  organization_id: string;
  permissions: Generated<Json>;
  provider: string;
  provider_installation_id: Int8;
  state: Generated<string>;
  suspended_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface PublishedFindings {
  created_at: Generated<Timestamp>;
  end_line: number | null;
  head_sha: string;
  id: Generated<string>;
  organization_id: string;
  path: string | null;
  placement: string;
  provider: string;
  provider_comment_id: string | null;
  provider_review_id: string | null;
  published_at: Timestamp;
  pull_request_id: string;
  review_run_id: string;
  start_line: number | null;
  updated_at: Generated<Timestamp>;
  verified_finding_id: string;
}

export interface PullRequests {
  author_login: string;
  base_ref: string;
  base_sha: string;
  created_at: Generated<Timestamp>;
  draft: Generated<boolean>;
  head_ref: string;
  head_sha: string;
  id: Generated<string>;
  merge_base_sha: string | null;
  organization_id: string;
  provider_number: number;
  repository_id: string;
  state: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Repositories {
  access_state: Generated<string>;
  archived: Generated<boolean>;
  created_at: Generated<Timestamp>;
  default_branch: string;
  enabled: Generated<boolean>;
  full_name: string;
  id: Generated<string>;
  initialized_at: Timestamp | null;
  installation_id: string;
  latest_init_facts_id: string | null;
  organization_id: string;
  primary_language: string | null;
  provider: string;
  provider_repo_id: string;
  settings: Generated<Json>;
  updated_at: Generated<Timestamp>;
  visibility: string;
}

export interface RepositoryConfigs {
  config_hash: string;
  created_at: Generated<Timestamp>;
  normalized: Json;
  organization_id: string;
  raw_blob_sha: string | null;
  repository_id: string;
  status: string;
  validation: Generated<Json>;
}

export interface RepositoryInitFacts {
  commit_sha: string;
  created_at: Generated<Timestamp>;
  detected_at: Timestamp;
  facts: Json;
  facts_hash: string;
  facts_schema_version: number;
  fingerprint: string | null;
  frameworks: Generated<string[]>;
  id: Generated<string>;
  is_monorepo: boolean;
  organization_id: string;
  primary_language: string | null;
  repository_id: string;
  tool_version: string;
  warnings_count: Generated<number>;
}

export interface RepositorySettings {
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  organization_id: string;
  repository_id: string;
  reviewer_overrides: Generated<Json>;
  skip_bots: Generated<boolean>;
  skip_drafts: Generated<boolean>;
  target_branches: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface ResolvedByKinds {
  id: number;
  name: string;
}

export interface ReviewerRuns {
  cached_read_tokens: Generated<Int8>;
  cached_write_tokens: Generated<Int8>;
  cluster_key: string | null;
  cost_usd_micros: Generated<Int8>;
  created_at: Generated<Timestamp>;
  error_class: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input_tokens: Generated<Int8>;
  latency_ms: number | null;
  model: string | null;
  organization_id: string;
  output_tokens: Generated<Int8>;
  prompt_version: string | null;
  provider: string | null;
  review_run_id: string;
  reviewer: string;
  reviewer_version: string | null;
  started_at: Timestamp | null;
  state: string;
  updated_at: Generated<Timestamp>;
}

export interface ReviewRuns {
  base_sha: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  degraded_reviewers: Generated<string[]>;
  failure_class: string | null;
  failure_detail: string | null;
  head_sha: string;
  id: Generated<string>;
  merge_base_sha: string | null;
  organization_id: string;
  provenance: Generated<Json>;
  pull_request_id: string;
  repository_id: string;
  retry_of: string | null;
  state: string;
  superseded_by: string | null;
  trace_parent: string | null;
  trigger: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  user_agent_hash: string | null;
  user_id: string;
}

export interface SnapshotFiles {
  change: string;
  file_version_id: Int8 | null;
  old_path: string | null;
  organization_id: string;
  path: string;
  snapshot_id: string;
}

export interface Snapshots {
  analyzer_versions: Json;
  base_snapshot_id: string | null;
  chain_depth: Generated<number>;
  commit_sha: string;
  completed_at: Timestamp | null;
  config_components: Generated<Json>;
  config_hash: Buffer;
  config_source_path: string | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  fingerprint: Buffer;
  graph_schema_version: number;
  id: string;
  kind: string;
  organization_id: string;
  purpose: string;
  repository_id: string;
  stats: Generated<Json>;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface SymbolLineage {
  from_key: Buffer;
  from_snapshot_id: string;
  id: Generated<Int8>;
  organization_id: string;
  repository_id: string;
  similarity: number;
  to_key: Buffer;
  to_snapshot_id: string;
  transition: string;
}

export interface Symbols {
  attrs: Generated<Json>;
  body_hash: Buffer | null;
  end_col: number;
  end_line: number;
  file_version_id: Int8;
  is_exported: Generated<boolean>;
  is_generated: Generated<boolean>;
  kind: number;
  name: string;
  organization_id: string;
  parent_key: Buffer | null;
  qualified_name: string;
  repository_id: string;
  signature: string | null;
  signature_hash: Buffer | null;
  start_col: number;
  start_line: number;
  symbol_id: string;
  symbol_key: Buffer;
  visibility: Generated<number>;
}

export interface SyntheticNodes {
  attrs: Generated<Json>;
  kind: number | null;
  node_id: string | null;
  node_key: Buffer;
  organization_id: string;
  removed: Generated<boolean>;
  snapshot_id: string;
}

export interface UnresolvedRefs {
  candidate_count: Generated<number>;
  col: number;
  file_version_id: Int8;
  from_symbol_key: Buffer | null;
  import_specifier: string | null;
  line: number;
  name: string;
  ordinal: number;
  organization_id: string;
  reason: number;
  ref_kind: number;
  repository_id: string;
  snapshot_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string | null;
  id: Generated<string>;
  login: string;
  provider: string;
  provider_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface VerifiedFindings {
  band: string;
  candidate_finding_id: string;
  computed_confidence: number;
  created_at: Generated<Timestamp>;
  evidence: Json;
  id: Generated<string>;
  organization_id: string;
  priority_score: number | null;
  review_run_id: string;
  severity: string;
  stage_outcomes: Json;
  updated_at: Generated<Timestamp>;
  verification_version: number;
}

export interface WebhookDeliveries {
  action: string | null;
  created_at: Generated<Timestamp>;
  delivery_id: string;
  error: string | null;
  event: string;
  id: Generated<string>;
  organization_id: string | null;
  payload_sha256: string;
  processed_at: Timestamp | null;
  provider: string;
  provider_installation_id: Int8 | null;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_log: AuditLog;
  candidate_findings: CandidateFindings;
  edge_kinds: EdgeKinds;
  file_versions: FileVersions;
  finding_feedback: FindingFeedback;
  graph_edges: GraphEdges;
  memberships: Memberships;
  model_cache: ModelCache;
  model_calls: ModelCalls;
  node_kinds: NodeKinds;
  organizations: Organizations;
  provenance_kinds: ProvenanceKinds;
  provider_installations: ProviderInstallations;
  published_findings: PublishedFindings;
  pull_requests: PullRequests;
  repositories: Repositories;
  repository_configs: RepositoryConfigs;
  repository_init_facts: RepositoryInitFacts;
  repository_settings: RepositorySettings;
  resolved_by_kinds: ResolvedByKinds;
  review_runs: ReviewRuns;
  reviewer_runs: ReviewerRuns;
  sessions: Sessions;
  snapshot_files: SnapshotFiles;
  snapshots: Snapshots;
  symbol_lineage: SymbolLineage;
  symbols: Symbols;
  synthetic_nodes: SyntheticNodes;
  unresolved_refs: UnresolvedRefs;
  users: Users;
  verified_findings: VerifiedFindings;
  webhook_deliveries: WebhookDeliveries;
}
