#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

//! DIFF-004 acceptance tests: binary, large, generated, vendored, minified and lockfile files.

use diff_engine::disposition::{
    classify_file, path_glob, DispositionRules, FileDisposition, GeneratedReason,
};
use diff_engine::files::{diff_commits, DiffOptions};
use diff_engine::git::ObjectHeader;
use diff_engine::model::DiffModel;
use diff_engine::testkit::{FileSpec, RepoBuilder};
use repository::manifests::Ecosystem;
use review_core::location::RepoPath;

fn path(p: &str) -> RepoPath {
    RepoPath::new(p).unwrap()
}

fn classify(p: &str, probe: &[u8], size: u64, rules: &DispositionRules) -> FileDisposition {
    let header = ObjectHeader { size };
    classify_file(
        &path(p),
        Some(&header),
        Some(&header),
        probe,
        b"",
        &rules.compile().unwrap(),
    )
}

fn model_with(base: &[FileSpec<'_>], head: &[FileSpec<'_>], opts: &DiffOptions) -> DiffModel {
    let mut repo = RepoBuilder::worktree().unwrap();
    let b = repo.commit("base", &[], base).unwrap();
    let h = repo.commit("head", std::slice::from_ref(&b), head).unwrap();
    let git = repo.open().unwrap();
    diff_commits(&git, &b, &h, opts).unwrap()
}

const PNG: &str = "\u{89}PNG\r\n\u{1a}\n\0\0\0\rIHDR\0\0\0\u{1}";

#[test]
fn png_is_binary_both_sides() {
    let model = model_with(
        &[FileSpec::file("logo.png", PNG)],
        &[FileSpec::file("logo.png", &format!("{PNG}\0\u{2}"))],
        &DiffOptions::default(),
    );
    let file = model.file("logo.png").unwrap();
    assert_eq!(file.disposition, FileDisposition::Binary);
    assert!(file.file.binary);
    assert!(file.hunks.is_empty());
    assert!(file.lines.is_none());

    // Text on the new side but binary on the old side is still binary (either side counts).
    let model = model_with(
        &[FileSpec::file("data.bin", PNG)],
        &[FileSpec::file("data.bin", "now text\n")],
        &DiffOptions::default(),
    );
    assert_eq!(
        model.file("data.bin").unwrap().disposition,
        FileDisposition::Binary
    );
}

#[test]
fn nul_byte_after_8k_not_binary() {
    let mut text = "x".repeat(79);
    text.push('\n');
    let mut content = text.repeat(101); // 8,080 bytes
    content.push('\0');
    let rules = DispositionRules::default();
    assert_eq!(
        classify(
            "notes.txt",
            content.as_bytes(),
            content.len() as u64,
            &rules
        ),
        FileDisposition::Analyze
    );
    let early = format!("ab\0{content}");
    assert_eq!(
        classify("notes.txt", early.as_bytes(), early.len() as u64, &rules),
        FileDisposition::Binary
    );
}

#[test]
fn three_mib_json_too_large() {
    let line = "{\"k\": \"value\"},\n";
    let big = line.repeat(3 * 1024 * 1024 / line.len() + 1);
    let model = model_with(
        &[FileSpec::file("data/big.json", "[]\n")],
        &[FileSpec::file("data/big.json", &big)],
        &DiffOptions::default(),
    );
    let file = model.file("data/big.json").unwrap();
    match file.disposition {
        FileDisposition::TooLarge { bytes, lines } => {
            assert_eq!(bytes, big.len() as u64);
            assert_eq!(lines, None);
        }
        other => panic!("expected TooLarge, got {other:?}"),
    }
    assert!(file.hunks.is_empty());
}

#[test]
fn line_cap_enforced_by_hunk_computation() {
    let many: String = (0..300).map(|i| format!("{i}\n")).collect();
    let mut opts = DiffOptions::default();
    opts.dispositions.max_diff_lines = 100;
    let model = model_with(
        &[FileSpec::file("src/many.ts", "0\n")],
        &[FileSpec::file("src/many.ts", &many)],
        &opts,
    );
    let file = model.file("src/many.ts").unwrap();
    assert_eq!(
        file.disposition,
        FileDisposition::TooLarge {
            bytes: many.len() as u64,
            lines: Some(300)
        }
    );
    assert!(file.hunks.is_empty());
    assert_eq!(model.stats.hunked_files, 0);
}

#[test]
fn generated_header_marker_detected() {
    let rules = DispositionRules::default();
    for header in [
        "// @generated by protoc\nexport const x = 1;\n",
        "// Code generated by sqlc. DO NOT EDIT.\n",
        "// <auto-generated />\n",
    ] {
        assert_eq!(
            classify("src/gen/api.ts", header.as_bytes(), 40, &rules),
            FileDisposition::Generated {
                reason: GeneratedReason::HeaderMarker
            },
            "{header}"
        );
    }
    // Beyond the first KiB the marker is ignored.
    let late = format!("{}// @generated\n", "x\n".repeat(600));
    assert_eq!(
        classify("src/late.ts", late.as_bytes(), 40, &rules),
        FileDisposition::Analyze
    );
}

#[test]
fn generated_glob_from_config() {
    let mut rules = DispositionRules::default();
    rules
        .generated_globs
        .push(path_glob("src/graphql/**").unwrap());
    assert_eq!(
        classify("src/graphql/types.ts", b"export type A = 1;\n", 20, &rules),
        FileDisposition::Generated {
            reason: GeneratedReason::PathGlob
        }
    );
    rules.generated_paths.insert(path("src/schema.ts"));
    assert_eq!(
        classify("src/schema.ts", b"export {};\n", 10, &rules),
        FileDisposition::Generated {
            reason: GeneratedReason::ConfigDeclared
        }
    );
}

#[test]
fn dist_bundle_vendored() {
    let rules = DispositionRules::default();
    for p in [
        "dist/main.js",
        "vendor/lib.js",
        "node_modules/left-pad/index.js",
        "packages/a/node_modules/x.js",
        "public/jquery.min.js",
    ] {
        assert_eq!(
            classify(p, b"var a=1;\n", 10, &rules),
            FileDisposition::Vendored,
            "{p}"
        );
    }
    assert_eq!(
        classify(
            "src/__snapshots__/a.snap",
            b"exports[`a`] = 1;\n",
            10,
            &rules
        ),
        FileDisposition::Analyze
    );
}

#[test]
fn minified_js_detected_by_line_length() {
    let rules = DispositionRules::default();
    let minified = format!("{}\n", "a=1;".repeat(1500));
    assert_eq!(
        classify(
            "src/bundle.js",
            minified.as_bytes(),
            minified.len() as u64,
            &rules
        ),
        FileDisposition::Minified
    );
    assert_eq!(
        classify("src/app.js", b"const a = 1;\nconst b = 2;\n", 26, &rules),
        FileDisposition::Analyze
    );
}

#[test]
fn package_lock_is_lockfile_summary() {
    let rules = DispositionRules::default();
    for (p, eco) in [
        ("package-lock.json", Ecosystem::Npm),
        ("apps/web/pnpm-lock.yaml", Ecosystem::Npm),
        ("yarn.lock", Ecosystem::Npm),
        ("Cargo.lock", Ecosystem::Cargo),
        ("go.sum", Ecosystem::Go),
    ] {
        assert_eq!(
            classify(p, b"{}\n", 3, &rules),
            FileDisposition::LockfileSummary { ecosystem: eco },
            "{p}"
        );
    }
}

#[test]
fn precedence_lockfile_over_generated() {
    let mut rules = DispositionRules::default();
    rules.generated_globs.push(path_glob("**").unwrap());
    assert_eq!(
        classify("package-lock.json", b"// @generated\n{}\n", 20, &rules),
        FileDisposition::LockfileSummary {
            ecosystem: Ecosystem::Npm
        }
    );
    // Vendored beats generated, generated beats binary.
    assert_eq!(
        classify("vendor/gen.js", b"// @generated\n", 20, &rules),
        FileDisposition::Vendored
    );
    assert_eq!(
        classify("src/gen.bin", b"// @generated\0\0", 20, &rules),
        FileDisposition::Generated {
            reason: GeneratedReason::PathGlob
        }
    );
}

fn mixed_model() -> DiffModel {
    let lock_old = "{\n  \"lockfileVersion\": 3\n}\n";
    let lock_new = "{\n  \"lockfileVersion\": 3,\n  \"packages\": {}\n}\n";
    model_with(
        &[
            FileSpec::file("package-lock.json", lock_old),
            FileSpec::file("src/app.ts", "export const a = 1;\n"),
            FileSpec::file("dist/main.js", "var a=1;\n"),
        ],
        &[
            FileSpec::file("package-lock.json", lock_new),
            FileSpec::file("src/app.ts", "export const a = 2;\n"),
            FileSpec::file("dist/main.js", "var a=2;\nvar b=3;\n"),
            FileSpec::file("src/gen.ts", "// @generated\nexport const g = 1;\n"),
        ],
        &DiffOptions::default(),
    )
}

#[test]
fn non_analyze_files_have_no_hunks_but_are_listed() {
    let model = mixed_model();
    assert_eq!(model.files.len(), 4);
    assert_eq!(model.stats.hunked_files, 1);
    for file in &model.files {
        if file.disposition.is_analyze() {
            assert!(!file.hunks.is_empty());
        } else {
            assert!(file.hunks.is_empty(), "{}", file.file.path.as_str());
            assert!(file.file.hunks.is_empty());
        }
    }
    // Cheap line statistics are still recorded for listed files.
    let dist = model.file("dist/main.js").unwrap();
    assert_eq!(dist.lines.map(|l| (l.additions, l.deletions)), Some((2, 1)));
}

#[test]
fn coverage_report_lists_reasons() {
    let model = mixed_model();
    let reasons: Vec<(String, &str)> = model
        .coverage
        .iter()
        .map(|c| (c.path.as_str().to_owned(), c.disposition.label()))
        .collect();
    assert_eq!(
        reasons,
        vec![
            ("dist/main.js".to_owned(), "vendored"),
            ("package-lock.json".to_owned(), "lockfile_summary"),
            ("src/gen.ts".to_owned(), "generated"),
        ]
    );
}

#[test]
fn vendored_override_via_config() {
    let mut rules = DispositionRules::default();
    rules.not_vendored.push(path_glob("dist/**").unwrap());
    rules.vendored_dirs.push(path_glob("legacy/**").unwrap());
    assert_eq!(
        classify("dist/main.js", b"var a=1;\n", 10, &rules),
        FileDisposition::Analyze
    );
    assert_eq!(
        classify("legacy/old.js", b"var a=1;\n", 10, &rules),
        FileDisposition::Vendored
    );
}
