#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::single_range_in_vec_init
)]

//! DIFF-007 edge-case scenarios. Binary and multi-MiB content is generated here rather than
//! committed; `fixtures/pull-requests/diff-edge-cases/` holds the description and the golden
//! dispositions.

mod support;

use std::collections::BTreeMap;

use diff_engine::model::DiffModel;
use diff_engine::symbol_map::{map_hunks, MapConfig};
use diff_engine::testkit::scenario::pull_requests_dir;
use diff_engine::testkit::Scenario;
use review_core::change::FileChangeStatus;
use review_core::location::DiffSide;
use serde_json::{json, Value};

const PNG: &str = "\u{89}PNG\r\n\u{1a}\n\0\0\0\rIHDR\0\0\0\u{1}";

fn trees() -> (BTreeMap<String, String>, BTreeMap<String, String>) {
    let twenty: String = (1..=20)
        .map(|i| format!("export const v{i} = {i};\n"))
        .collect();
    let mut base = BTreeMap::new();
    let mut head = BTreeMap::new();
    let mut both = |p: &str, b: &str, h: &str| {
        base.insert(p.to_owned(), b.to_owned());
        head.insert(p.to_owned(), h.to_owned());
    };
    both("assets/logo.png", PNG, &format!("{PNG}\0\u{2}"));
    both(
        "src/app.ts",
        "export const a = 1;\n",
        "export const a = 2;\n",
    );
    both(
        "src/crlf.ts",
        "export const x = 1;\nexport const y = 2;\nexport const z = 3;\n",
        "export const x = 1;\r\nexport const y = 2;\r\nexport const z = 3;\r\n",
    );
    both(
        "src/move_from.ts",
        "export function stays(): number {\n  return 1;\n}\n\nexport function helper(): number {\n  return 2;\n}\n",
        "export function stays(): number {\n  return 1;\n}\n",
    );
    both(
        "src/move_to.ts",
        "export function other(): number {\n  return 3;\n}\n",
        "export function other(): number {\n  return 3;\n}\n\nexport function helper(): number {\n  return 2;\n}\n",
    );
    both(
        "package-lock.json",
        "{\n  \"lockfileVersion\": 3\n}\n",
        "{\n  \"lockfileVersion\": 3,\n  \"packages\": {}\n}\n",
    );
    both("dist/bundle.js", "var a=1;\n", "var a=2;\n");
    both(
        "vendor/lib.js",
        "module.exports = 1;\n",
        "module.exports = 2;\n",
    );

    base.insert(
        "src/remove_me.ts".to_owned(),
        "export function obsolete(): number {\n  return 42;\n}\n".to_owned(),
    );
    let pure = "export const pure = 'rename';\nexport const kept = true;\n";
    base.insert("src/old_name.ts".to_owned(), pure.to_owned());
    head.insert("src/new_name.ts".to_owned(), pure.to_owned());
    base.insert("src/util/a.ts".to_owned(), twenty.clone());
    head.insert(
        "src/util/b.ts".to_owned(),
        twenty.replace("export const v10 = 10;\n", "export const v10 = 100;\n"),
    );
    head.insert(
        "data/big.json".to_owned(),
        "0123456789abcde\n".repeat(196_608),
    );
    head.insert(
        "src/legacy/app.js".to_owned(),
        format!("{}\n", "a=1;".repeat(1500)),
    );
    head.insert(
        "src/gen/client.ts".to_owned(),
        "// @generated by openapi\nexport const client = 1;\n".to_owned(),
    );
    (base, head)
}

fn scenario() -> (Scenario, DiffModel) {
    let (base, head) = trees();
    let scenario = Scenario::from_trees(
        "diff-edge-cases",
        pull_requests_dir().join("diff-edge-cases"),
        base,
        head,
    )
    .unwrap();
    let diff = support::diff_scenario(&scenario);
    (scenario, diff)
}

fn status(diff: &DiffModel, path: &str) -> FileChangeStatus {
    diff.file(path)
        .unwrap_or_else(|| panic!("missing {path}"))
        .file
        .status
}

#[test]
fn edge_pure_rename_has_no_hunks() {
    let (_, diff) = scenario();
    let file = diff.file("src/new_name.ts").unwrap();
    assert_eq!(file.file.status, FileChangeStatus::Renamed);
    assert_eq!(
        file.file.old_path.as_ref().map(|p| p.as_str()),
        Some("src/old_name.ts")
    );
    assert!(file.hunks.is_empty());
    assert_eq!(file.lines.map(|l| (l.additions, l.deletions)), Some((0, 0)));
}

#[test]
fn edge_rename_with_edit_old_path_diffed() {
    let (_, diff) = scenario();
    let file = diff.file("src/util/b.ts").unwrap();
    assert_eq!(file.file.status, FileChangeStatus::Renamed);
    assert_eq!(
        file.file.old_path.as_ref().map(|p| p.as_str()),
        Some("src/util/a.ts")
    );
    assert_eq!(file.hunks.len(), 1);
    assert_eq!(file.lines.map(|l| (l.additions, l.deletions)), Some((1, 1)));
}

#[test]
fn edge_deleted_file_symbols_from_base() {
    let (scenario, diff) = scenario();
    assert_eq!(status(&diff, "src/remove_me.ts"), FileChangeStatus::Deleted);
    let units = support::units_for(&scenario, &diff);
    let map = map_hunks(&diff, &units, &MapConfig::default());
    let hits: Vec<_> = map.hits_in("src/remove_me.ts").collect();
    assert_eq!(hits.len(), 1, "{hits:?}");
    assert_eq!(hits[0].side, DiffSide::Base);
    assert_eq!(
        hits[0].symbol_id.as_str(),
        "ts:src/remove_me#obsolete/function"
    );
    assert!(hits[0].whole_symbol);
}

fn dispositions(diff: &DiffModel) -> Value {
    Value::Array(
        diff.files
            .iter()
            .map(|f| {
                json!({
                    "path": f.file.path.as_str(),
                    "status": f.file.status,
                    "disposition": f.disposition,
                    "hunks": f.hunks.len(),
                })
            })
            .collect(),
    )
}

#[test]
fn edge_binary_and_large_have_dispositions() {
    let (scenario, diff) = scenario();
    support::assert_golden(
        scenario.dir.join("expected/dispositions.json"),
        &dispositions(&diff),
    );
    let png = diff.file("assets/logo.png").unwrap();
    assert!(png.file.binary);
    let coverage: Vec<&str> = diff.coverage.iter().map(|c| c.path.as_str()).collect();
    assert_eq!(
        coverage,
        vec![
            "assets/logo.png",
            "data/big.json",
            "dist/bundle.js",
            "package-lock.json",
            "src/gen/client.ts",
            "src/legacy/app.js",
            "vendor/lib.js",
        ]
    );
}

#[test]
fn edge_crlf_conversion_reports_every_line() {
    let (_, diff) = scenario();
    let file = diff.file("src/crlf.ts").unwrap();
    assert_eq!(file.lines.map(|l| (l.additions, l.deletions)), Some((3, 3)));
}

#[test]
fn edge_symbol_move_between_files_two_hits() {
    let (scenario, diff) = scenario();
    let units = support::units_for(&scenario, &diff);
    let map = map_hunks(&diff, &units, &MapConfig::default());
    let removed = map
        .hit("ts:src/move_from#helper/function")
        .unwrap_or_else(|| panic!("{:?}", map.hits));
    assert_eq!(removed.side, DiffSide::Base);
    assert!(removed.whole_symbol);
    let added = map.hit("ts:src/move_to#helper/function").unwrap();
    assert_eq!(added.side, DiffSide::Head);
    assert!(added.whole_symbol);
}
