/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/github/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_login'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/github/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_callback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RepositoriesController_list'];
    put?: never;
    post: operations['RepositoriesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RepositoriesController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}/initialize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RepositoriesController_initialize'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RepositoriesController_status'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RepositoriesController_profile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}/graph/rebuild': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RepositoriesController_rebuild'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/repositories/{repoId}/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['RepositoriesController_updateSettings'];
    trace?: never;
  };
  '/api/v1/webhooks/github': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['GithubWebhookController_receive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_live'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthAliasController_alias'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateRepositoryDto: {
      /** Format: uuid */
      installation_id: string;
      full_name: string;
    };
    RepositoryDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      /** @enum {string} */
      provider: 'github';
      provider_repo_id: string;
      full_name: string;
      default_branch: string;
      /** @enum {string} */
      visibility: 'public' | 'private' | 'internal';
      archived: boolean;
      enabled: boolean;
      /** @enum {string} */
      access_state: 'active' | 'removed' | 'access_lost' | 'installation_deleted';
      primary_language: string[];
      initialized_at: string[];
      settings: {
        enabled: boolean;
        target_branches: string[];
        skip_drafts: boolean;
        skip_bots: boolean;
        reviewer_overrides: {
          [key: string]: boolean;
        };
      };
      created_at: string;
      updated_at: string;
    };
    RepositoryListDto: {
      items: {
        /** Format: uuid */
        id: string;
        /** Format: uuid */
        organization_id: string;
        /** @enum {string} */
        provider: 'github';
        provider_repo_id: string;
        full_name: string;
        default_branch: string;
        /** @enum {string} */
        visibility: 'public' | 'private' | 'internal';
        archived: boolean;
        enabled: boolean;
        /** @enum {string} */
        access_state: 'active' | 'removed' | 'access_lost' | 'installation_deleted';
        primary_language: string | null;
        initialized_at: string | null;
        settings: {
          enabled: boolean;
          target_branches: string[];
          skip_drafts: boolean;
          skip_bots: boolean;
          reviewer_overrides: {
            [key: string]: boolean;
          };
        };
        created_at: string;
        updated_at: string;
      }[];
      next_cursor: string[];
    };
    IndexRequestDto: {
      job_id: string;
      idempotency_key: string;
      head_sha: string;
    };
    RepositoryStatusDto: {
      /** Format: uuid */
      repository_id: string;
      /** @enum {string} */
      index_state: 'not_initialized' | 'queued' | 'indexing' | 'ready';
      init: {
        commit_sha: string;
        fingerprint: string | null;
        facts_hash: string;
        facts_schema_version: number;
        tool_version: string;
        primary_language: string | null;
        is_monorepo: boolean;
        frameworks: string[];
        warnings_count: number;
        detected_at: string;
      } | null;
      last_snapshot: {
        full: {
          id: string;
          commit_sha: string;
          created_at: string;
        } | null;
        delta: {
          id: string;
          commit_sha: string;
          created_at: string;
        } | null;
      } | null;
      active_job: {
        id: string;
        queue: string;
        /** @enum {string} */
        state: 'queued' | 'running';
      } | null;
      config: {
        hash: string | null;
        validation_errors: string[];
      };
      profile_computed_at: string[];
    };
    UpdateRepositorySettingsDto: {
      enabled?: boolean;
      target_branches?: string[];
      skip_drafts?: boolean;
      skip_bots?: boolean;
      reviewer_overrides?: {
        [key: string]: boolean;
      };
    };
    RepositorySettingsDto: {
      enabled: boolean;
      target_branches: string[];
      skip_drafts: boolean;
      skip_bots: boolean;
      reviewer_overrides: {
        [key: string]: boolean;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_callback: {
    parameters: {
      query: {
        code: string;
        state: string;
        error: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RepositoriesController_list: {
    parameters: {
      query?: {
        organization_id?: string;
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryListDto'];
        };
      };
    };
  };
  RepositoriesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRepositoryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryDto'];
        };
      };
    };
  };
  RepositoriesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryDto'];
        };
      };
    };
  };
  RepositoriesController_initialize: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IndexRequestDto'];
        };
      };
    };
  };
  RepositoriesController_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryStatusDto'];
        };
      };
    };
  };
  RepositoriesController_profile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The repository profile (PROF-001). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RepositoriesController_rebuild: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IndexRequestDto'];
        };
      };
    };
  };
  RepositoriesController_updateSettings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repoId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRepositorySettingsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositorySettingsDto'];
        };
      };
    };
  };
  GithubWebhookController_receive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthAliasController_alias: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
