//! File dispositions (DIFF-004): classify every changed file before hunk computation.
//!
//! Precedence, first match wins: `LockfileSummary` > `Vendored` > `Generated` (declared path,
//! path glob, then a header marker in the first KiB) > `Binary` (NUL byte in the first 8,000
//! bytes of either side, git's rule) > `TooLarge` (blob size from the object header) >
//! `Minified` (long lines in the probe) > `Analyze`. Classification is a pure function of the
//! path, the object headers, a bounded content probe and the [`DispositionRules`].

use std::collections::BTreeSet;

use globset::{Glob, GlobBuilder, GlobSet, GlobSetBuilder};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use repository::generated::{GeneratedFacts, GeneratedKind};
use repository::manifests::Ecosystem;
use review_core::location::RepoPath;

use crate::git::ObjectHeader;

/// Bytes of content inspected for binary and minified detection.
pub const PROBE_BYTES: usize = 8 * 1024;
/// Bytes scanned for NUL (git's `FIRST_FEW_BYTES`).
pub const BINARY_SCAN_BYTES: usize = 8000;
/// Bytes scanned for generated-code header markers.
pub const MARKER_SCAN_BYTES: usize = 1024;
/// Literal markers that flag a generated file.
pub const GENERATED_MARKERS: [&str; 3] = ["@generated", "DO NOT EDIT", "<auto-generated"];

/// What the diff pipeline should do with a changed file.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum FileDisposition {
    /// Diff, map symbols and analyse the file normally.
    #[default]
    Analyze,
    /// Binary content: listed but never diffed or analysed.
    Binary,
    /// Over the configured size or line caps.
    TooLarge {
        /// Size of the changed blob in bytes (from the object header, not inflated).
        bytes: u64,
        /// Line count when known cheaply.
        lines: Option<u32>,
    },
    /// Generated by a tool (bundle, codegen); listed with its reason.
    Generated {
        /// Why the file was classified as generated.
        reason: GeneratedReason,
    },
    /// Third-party code under a vendored directory.
    Vendored,
    /// Single-line (minified) JavaScript or CSS.
    Minified,
    /// A dependency lockfile; summarised rather than line-diffed.
    LockfileSummary {
        /// Package ecosystem the lockfile belongs to.
        ecosystem: Ecosystem,
    },
    /// The content probe could not be read; the file is listed but not analysed.
    Unreadable,
}

impl FileDisposition {
    /// Whether hunks and symbols are computed for the file.
    pub fn is_analyze(&self) -> bool {
        matches!(self, Self::Analyze)
    }

    /// Stable metric/summary label.
    pub fn label(&self) -> &'static str {
        match self {
            Self::Analyze => "analyze",
            Self::Binary => "binary",
            Self::TooLarge { .. } => "too_large",
            Self::Generated { .. } => "generated",
            Self::Vendored => "vendored",
            Self::Minified => "minified",
            Self::LockfileSummary { .. } => "lockfile_summary",
            Self::Unreadable => "unreadable",
        }
    }
}

/// Why a file was classified as [`FileDisposition::Generated`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedReason {
    /// Matched a generated-path glob from `.review` config or INIT-008 defaults.
    PathGlob,
    /// Carried a `@generated`-style marker header.
    HeaderMarker,
    /// Declared in the repository's generated-code config.
    ConfigDeclared,
}

/// Classification rules; `.review/config.yaml` (POL-001) supplies overrides.
#[derive(Debug, Clone, PartialEq)]
pub struct DispositionRules {
    /// Larger blobs are `TooLarge` (1 MiB).
    pub max_diff_bytes: u64,
    /// Files with more lines are `TooLarge` (20,000), enforced by hunk computation.
    pub max_diff_lines: u32,
    /// Vendored path globs (defaults: [`DispositionRules::DEFAULT_VENDORED`]).
    pub vendored_dirs: Vec<Glob>,
    /// Globs removed from the vendored set (a repository override wins over the defaults).
    pub not_vendored: Vec<Glob>,
    /// Generated-path globs (`.review/config.yaml` `generated.include`).
    pub generated_globs: Vec<Glob>,
    /// Paths INIT-008 already classified as generated for this repository.
    pub generated_paths: BTreeSet<RepoPath>,
    /// Extra lockfile globs beyond the built-in file names.
    pub lockfiles: Vec<(Glob, Ecosystem)>,
}

impl DispositionRules {
    /// Default vendored directories and files.
    pub const DEFAULT_VENDORED: [&'static str; 7] = [
        "**/node_modules/**",
        "**/vendor/**",
        "**/third_party/**",
        "dist/**",
        "build/**",
        ".yarn/**",
        "**/*.min.js",
    ];

    /// Adds the files INIT-008 classified as generated (vendored and lockfile verdicts are
    /// re-derived from the rules here, so only `Generated` entries are taken).
    pub fn with_generated_facts(mut self, facts: &GeneratedFacts) -> Self {
        for (path, class) in &facts.files {
            if class.kind == GeneratedKind::Generated {
                self.generated_paths.insert(path.clone());
            }
        }
        self
    }

    /// Compiles the glob sets once so classification is O(1) per file in the number of rules.
    pub fn compile(&self) -> Result<CompiledRules, globset::Error> {
        let mut lockfile_sets = Vec::with_capacity(self.lockfiles.len());
        for (glob, eco) in &self.lockfiles {
            lockfile_sets.push((glob.compile_matcher(), *eco));
        }
        Ok(CompiledRules {
            vendored: build_set(&self.vendored_dirs)?,
            not_vendored: build_set(&self.not_vendored)?,
            generated: build_set(&self.generated_globs)?,
            lockfiles: lockfile_sets,
            generated_paths: self.generated_paths.clone(),
            max_diff_bytes: self.max_diff_bytes,
        })
    }
}

impl Default for DispositionRules {
    fn default() -> Self {
        Self {
            max_diff_bytes: 1024 * 1024,
            max_diff_lines: 20_000,
            vendored_dirs: Self::DEFAULT_VENDORED
                .iter()
                .filter_map(|g| path_glob(g).ok())
                .collect(),
            not_vendored: Vec::new(),
            generated_globs: Vec::new(),
            generated_paths: BTreeSet::new(),
            lockfiles: Vec::new(),
        }
    }
}

/// A glob where `*` does not cross `/` (git pathspec semantics).
pub fn path_glob(pattern: &str) -> Result<Glob, globset::Error> {
    GlobBuilder::new(pattern).literal_separator(true).build()
}

fn build_set(globs: &[Glob]) -> Result<GlobSet, globset::Error> {
    let mut builder = GlobSetBuilder::new();
    for glob in globs {
        builder.add(glob.clone());
    }
    builder.build()
}

/// [`DispositionRules`] with compiled matchers.
#[derive(Debug, Clone)]
pub struct CompiledRules {
    vendored: GlobSet,
    not_vendored: GlobSet,
    generated: GlobSet,
    lockfiles: Vec<(globset::GlobMatcher, Ecosystem)>,
    generated_paths: BTreeSet<RepoPath>,
    max_diff_bytes: u64,
}

/// Built-in lockfile names.
pub fn lockfile_ecosystem(path: &str) -> Option<Ecosystem> {
    let name = path.rsplit('/').next().unwrap_or(path);
    let eco = match name {
        "package-lock.json"
        | "npm-shrinkwrap.json"
        | "pnpm-lock.yaml"
        | "yarn.lock"
        | "bun.lock"
        | "bun.lockb" => Ecosystem::Npm,
        "Cargo.lock" => Ecosystem::Cargo,
        "poetry.lock" | "uv.lock" | "Pipfile.lock" | "pdm.lock" => Ecosystem::Pypi,
        "go.sum" => Ecosystem::Go,
        "composer.lock" => Ecosystem::Composer,
        "Gemfile.lock" => Ecosystem::Rubygems,
        "packages.lock.json" => Ecosystem::Nuget,
        "gradle.lockfile" => Ecosystem::Gradle,
        _ => return None,
    };
    Some(eco)
}

/// Classify one changed file. `probe` holds the first bytes of the new side (or the old side
/// for deletions); `old_probe` the first bytes of the old side when both exist, so binary
/// detection sees either side.
pub fn classify_file(
    path: &RepoPath,
    old: Option<&ObjectHeader>,
    new: Option<&ObjectHeader>,
    probe: &[u8],
    old_probe: &[u8],
    rules: &CompiledRules,
) -> FileDisposition {
    let p = path.as_str();
    if let Some(ecosystem) = lockfile_ecosystem(p) {
        return FileDisposition::LockfileSummary { ecosystem };
    }
    if let Some((_, ecosystem)) = rules.lockfiles.iter().find(|(m, _)| m.is_match(p)) {
        return FileDisposition::LockfileSummary {
            ecosystem: *ecosystem,
        };
    }
    if rules.vendored.is_match(p) && !rules.not_vendored.is_match(p) {
        return FileDisposition::Vendored;
    }
    if rules.generated_paths.contains(path) {
        return FileDisposition::Generated {
            reason: GeneratedReason::ConfigDeclared,
        };
    }
    if rules.generated.is_match(p) {
        return FileDisposition::Generated {
            reason: GeneratedReason::PathGlob,
        };
    }
    if has_generated_marker(probe) {
        return FileDisposition::Generated {
            reason: GeneratedReason::HeaderMarker,
        };
    }
    if is_binary(probe) || is_binary(old_probe) {
        return FileDisposition::Binary;
    }
    let bytes = new
        .map(|h| h.size)
        .unwrap_or(0)
        .max(old.map(|h| h.size).unwrap_or(0));
    if bytes > rules.max_diff_bytes {
        return FileDisposition::TooLarge { bytes, lines: None };
    }
    if is_minified(probe) {
        return FileDisposition::Minified;
    }
    FileDisposition::Analyze
}

/// A NUL byte within the first 8,000 bytes (git's binary heuristic).
pub fn is_binary(probe: &[u8]) -> bool {
    probe.iter().take(BINARY_SCAN_BYTES).any(|b| *b == 0)
}

/// A literal generated-code marker within the first KiB.
pub fn has_generated_marker(probe: &[u8]) -> bool {
    let head = &probe[..probe.len().min(MARKER_SCAN_BYTES)];
    GENERATED_MARKERS
        .iter()
        .any(|marker| contains(head, marker.as_bytes()))
}

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    !needle.is_empty() && haystack.windows(needle.len()).any(|w| w == needle)
}

/// Average line length above 500 bytes, or any line above 5,000 bytes, within the probe.
pub fn is_minified(probe: &[u8]) -> bool {
    if probe.is_empty() {
        return false;
    }
    let mut lines = 0usize;
    let mut longest = 0usize;
    let mut current = 0usize;
    for b in probe.iter().take(PROBE_BYTES) {
        if *b == b'\n' {
            lines += 1;
            longest = longest.max(current);
            current = 0;
        } else {
            current += 1;
        }
    }
    longest = longest.max(current);
    if current > 0 {
        lines += 1;
    }
    let total = probe.len().min(PROBE_BYTES);
    longest > 5_000 || (lines > 0 && total / lines > 500)
}

/// A file that was not analysed and why, for `DiffModel::coverage`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CoverageEntry {
    /// The file.
    pub path: RepoPath,
    /// Its disposition (never `Analyze`).
    pub disposition: FileDisposition,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compiled() -> CompiledRules {
        match DispositionRules::default().compile() {
            Ok(rules) => rules,
            Err(e) => unreachable!("default rules compile: {e}"),
        }
    }

    fn path(p: &str) -> RepoPath {
        match RepoPath::new(p) {
            Ok(p) => p,
            Err(e) => unreachable!("valid path: {e}"),
        }
    }

    #[test]
    fn default_vendored_globs() {
        let rules = compiled();
        let header = ObjectHeader { size: 10 };
        for p in ["node_modules/x/index.js", "vendor/lib.js", "dist/main.js"] {
            assert_eq!(
                classify_file(&path(p), None, Some(&header), b"x", b"", &rules),
                FileDisposition::Vendored,
                "{p}"
            );
        }
        assert_eq!(
            classify_file(&path("src/dist.ts"), None, Some(&header), b"x", b"", &rules),
            FileDisposition::Analyze
        );
    }

    #[test]
    fn minified_heuristics() {
        assert!(is_minified(&[b'a'; 6000]));
        assert!(!is_minified(b"a\nb\n"));
    }
}
