//! File dispositions (DIFF-004 will implement classification logic; DIFF-002 only defines the
//! type so `FileDiff` carries its final shape).

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use repository::manifests::Ecosystem;

/// What the diff pipeline should do with a changed file.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum FileDisposition {
    /// Diff, map symbols and analyse the file normally.
    #[default]
    Analyze,
    /// Binary content: listed but never diffed or analysed.
    Binary,
    /// Over the configured size or line caps.
    TooLarge {
        /// Size of the changed blob in bytes (from the object header, not inflated).
        bytes: u64,
        /// Line count when known cheaply.
        lines: Option<u32>,
    },
    /// Generated by a tool (bundle, codegen); listed with its reason.
    Generated {
        /// Why the file was classified as generated.
        reason: GeneratedReason,
    },
    /// Third-party code under a vendored directory.
    Vendored,
    /// Single-line (minified) JavaScript or CSS.
    Minified,
    /// A dependency lockfile; summarised rather than line-diffed.
    LockfileSummary {
        /// Package ecosystem the lockfile belongs to.
        ecosystem: Ecosystem,
    },
}

/// Why a file was classified as [`FileDisposition::Generated`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedReason {
    /// Matched a generated-path glob from `.review` config or INIT-008 defaults.
    PathGlob,
    /// Carried a `@generated`-style marker header.
    HeaderMarker,
    /// Declared in the repository's generated-code config.
    ConfigDeclared,
}
